### ISSUE TITLE
confront our visions for the project

### ISSUE THREAD

**Issue by yactouat-reboot** [reboot-conseil/ilot-frais-v2#1]
Every member should =>

- give his vision of what we are to build
- with what tools we are going to do it
- what main steps are ahead

Don't forget the specifics of the requirement => https://docker.devpost.com/

**Comment by yactouat-reboot** [comment]
### VISION

- a pipeline that re trains an AI model on a dataset that is augmented by user inputs and feedback in app'

### TOOLS

- a CI platform
- AI/ML Python libs such as `pytorch` or TensorFlow
- some frontend code for user input

## STEPS

- define what input we want from the users regarding our business logic
- train a baseline model on that kind of input
- put together a pipeline for re training based on that input

**Comment by celiafritsch** [comment]
Vision : 
Avec l'IA, on peut estimer la température ou au moins les zones très chaudes (sans arbres, sans eau, très urbanisés/goudronnées)

Avec un algo, on peut déterminer la distance à une source de fraîcheur pour les habitants/salariés


Tools :
Python (pytorch ou tensorflow : je connais pas bien la différence)


Steps : 
- Dans l'idéal, il faudrait trouver des cartes avec des températures
- Mais on pourrait aussi juste avoir une image GPS et faire de la classification (IA non supervisé) pour identifier les zones sur la cartes

- On peut aussi chercher s'il y a déjà un calcul approximatif pour estimer la différence de température en fronction des éléments ou de la distance à une source de fraicheur ?
